fix: use `mongodb` 3.3.0 from crates.io (#5668)
The commit that we used a git dependency for `mongodb` for was merged to
`main` and published to crates.io in August 2024.

Some CI workflows suddenly started failing with this error:

```
error: failed to get `mongodb` as a dependency of package `mongodb-schema-connector v0.1.0 (/home/runner/work/prisma-engines/prisma-engines/schema-engine/connectors/mongodb-schema-connector)`

Caused by:
  failed to load source for dependency `mongodb`

Caused by:
  Unable to update https://github.com/prisma/mongo-rust-driver.git?branch=RUST-1994%2Fhappy-eyeballs#31e03563

Caused by:
  failed to clone into: /home/runner/.cargo/git/db/mongo-rust-driver-bba754b690866f21

Caused by:
  revision 31e0356391a7871bec000ae35fe0edc35582449e not found
```

which is a good reminder that we should have switched back to the normal
crates.io dependency long time ago.

This also resolves a [high severity dependabot security
alert](https://github.com/prisma/prisma-engines/security/dependabot/91).